package TicTacToe;

import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author gian_
 */
public class Game extends javax.swing.JFrame {

    GameFunctions gameFunctions = new GameFunctions();

    /**
     * Creates new form game
     */
    public Game() {
        initComponents();
        this.GanhadorLBL.setVisible(false);
        this.GanhadorLBL.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GanhadorLBL = new javax.swing.JLabel();
        Campo1LBL = new javax.swing.JLabel();
        Campo2LBL = new javax.swing.JLabel();
        Campo3LBL = new javax.swing.JLabel();
        Campo4LBL = new javax.swing.JLabel();
        Campo5LBL = new javax.swing.JLabel();
        Campo6LBL = new javax.swing.JLabel();
        Campo7LBL = new javax.swing.JLabel();
        Campo8LBL = new javax.swing.JLabel();
        Campo9LBL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 370, 370));
        setMaximumSize(new java.awt.Dimension(380, 380));
        setMinimumSize(new java.awt.Dimension(380, 380));
        setResizable(false);
        setSize(new java.awt.Dimension(380, 380));

        GanhadorLBL.setBackground(new java.awt.Color(255, 255, 255));
        GanhadorLBL.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        GanhadorLBL.setForeground(new java.awt.Color(0, 0, 0));
        GanhadorLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        GanhadorLBL.setOpaque(true);

        Campo1LBL.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Campo1LBL.setForeground(new java.awt.Color(0, 0, 0));
        Campo1LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Campo1LBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Campo1LBLMouseClicked(evt);
            }
        });

        Campo2LBL.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Campo2LBL.setForeground(new java.awt.Color(0, 0, 0));
        Campo2LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Campo2LBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Campo2LBLMouseClicked(evt);
            }
        });

        Campo3LBL.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Campo3LBL.setForeground(new java.awt.Color(0, 0, 0));
        Campo3LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Campo3LBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Campo3LBLMouseClicked(evt);
            }
        });

        Campo4LBL.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Campo4LBL.setForeground(new java.awt.Color(0, 0, 0));
        Campo4LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Campo4LBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Campo4LBLMouseClicked(evt);
            }
        });

        Campo5LBL.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Campo5LBL.setForeground(new java.awt.Color(0, 0, 0));
        Campo5LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Campo5LBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Campo5LBLMouseClicked(evt);
            }
        });

        Campo6LBL.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Campo6LBL.setForeground(new java.awt.Color(0, 0, 0));
        Campo6LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Campo6LBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Campo6LBLMouseClicked(evt);
            }
        });

        Campo7LBL.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Campo7LBL.setForeground(new java.awt.Color(0, 0, 0));
        Campo7LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Campo7LBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Campo7LBLMouseClicked(evt);
            }
        });

        Campo8LBL.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Campo8LBL.setForeground(new java.awt.Color(0, 0, 0));
        Campo8LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Campo8LBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Campo8LBLMouseClicked(evt);
            }
        });

        Campo9LBL.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Campo9LBL.setForeground(new java.awt.Color(0, 0, 0));
        Campo9LBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Campo9LBL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Campo9LBLMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Campo1LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(Campo3LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(Campo6LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(Campo4LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(GanhadorLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Campo7LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(Campo9LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(Campo2LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(Campo8LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(Campo5LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Campo1LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Campo3LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Campo6LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Campo4LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(GanhadorLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Campo7LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(Campo9LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Campo2LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(Campo8LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(Campo5LBL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Campo1LBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Campo1LBLMouseClicked
        String acabouContinua = this.AcabouOuContinua(1);
        String texto = acabouContinua == null ? this.Campo1LBL.getText() : acabouContinua;
        this.Campo1LBL.setText(texto);
    }//GEN-LAST:event_Campo1LBLMouseClicked

    private void Campo2LBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Campo2LBLMouseClicked
        String acabouContinua = this.AcabouOuContinua(2);
        String texto = acabouContinua == null ? this.Campo2LBL.getText() : acabouContinua;
        this.Campo2LBL.setText(texto);
    }//GEN-LAST:event_Campo2LBLMouseClicked

    private void Campo3LBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Campo3LBLMouseClicked
        String acabouContinua = this.AcabouOuContinua(3);
        String texto = acabouContinua == null ? this.Campo3LBL.getText() : acabouContinua;
        this.Campo3LBL.setText(texto);
    }//GEN-LAST:event_Campo3LBLMouseClicked

    private void Campo4LBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Campo4LBLMouseClicked
        String acabouContinua = this.AcabouOuContinua(4);
        String texto = acabouContinua == null ? this.Campo4LBL.getText() : acabouContinua;
        this.Campo4LBL.setText(texto);
    }//GEN-LAST:event_Campo4LBLMouseClicked

    private void Campo5LBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Campo5LBLMouseClicked
        String acabouContinua = this.AcabouOuContinua(5);
        String texto = acabouContinua == null ? this.Campo5LBL.getText() : acabouContinua;
        this.Campo5LBL.setText(texto);
    }//GEN-LAST:event_Campo5LBLMouseClicked

    private void Campo6LBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Campo6LBLMouseClicked
        String acabouContinua = this.AcabouOuContinua(6);
        String texto = acabouContinua == null ? this.Campo6LBL.getText() : acabouContinua;
        this.Campo6LBL.setText(texto);
    }//GEN-LAST:event_Campo6LBLMouseClicked

    private void Campo7LBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Campo7LBLMouseClicked
        String acabouContinua = this.AcabouOuContinua(7);
        String texto = acabouContinua == null ? this.Campo7LBL.getText() : acabouContinua;
        this.Campo7LBL.setText(texto);
    }//GEN-LAST:event_Campo7LBLMouseClicked

    private void Campo8LBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Campo8LBLMouseClicked
        String acabouContinua = this.AcabouOuContinua(8);
        String texto = acabouContinua == null ? this.Campo8LBL.getText() : acabouContinua;
        this.Campo8LBL.setText(texto);
    }//GEN-LAST:event_Campo8LBLMouseClicked

    private void Campo9LBLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Campo9LBLMouseClicked
        String acabouContinua = this.AcabouOuContinua(9);
        String texto = acabouContinua == null ? this.Campo9LBL.getText() : acabouContinua;
        this.Campo9LBL.setText(texto);
    }//GEN-LAST:event_Campo9LBLMouseClicked

    private String AcabouOuContinua(int posicao) {
        if (this.GanhadorLBL.isEnabled()) {
            return null;
        }
        
        String acabou = this.gameFunctions.Play(posicao);

        if (acabou == "1" || acabou == "0" || acabou == "velha") {
            this.Campo1LBL.setEnabled(false);
            this.Campo2LBL.setEnabled(false);
            this.Campo3LBL.setEnabled(false);
            this.Campo4LBL.setEnabled(false);
            this.Campo5LBL.setEnabled(false);
            this.Campo6LBL.setEnabled(false);
            this.Campo7LBL.setEnabled(false);
            this.Campo8LBL.setEnabled(false);
            this.Campo9LBL.setEnabled(false);

            if (acabou == "1") {
                this.GanhadorLBL.setText("X Ganhou");
                acabou = "X";
                this.GanhadorLBL.setVisible(true);
                this.GanhadorLBL.setEnabled(true);
            } else if (acabou == "0") {
                this.GanhadorLBL.setText("O Ganhou");
                acabou = "O";
                this.GanhadorLBL.setVisible(true);
                this.GanhadorLBL.setEnabled(true);
            } else {
                this.GanhadorLBL.setText("Deu Velha");
                acabou = "X";
                this.GanhadorLBL.setVisible(true);
                this.GanhadorLBL.setEnabled(true);
            }
        }

        return acabou;

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Campo1LBL;
    private javax.swing.JLabel Campo2LBL;
    private javax.swing.JLabel Campo3LBL;
    private javax.swing.JLabel Campo4LBL;
    private javax.swing.JLabel Campo5LBL;
    private javax.swing.JLabel Campo6LBL;
    private javax.swing.JLabel Campo7LBL;
    private javax.swing.JLabel Campo8LBL;
    private javax.swing.JLabel Campo9LBL;
    private javax.swing.JLabel GanhadorLBL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
